### ISSUE TITLE
Reenabling Trigger causes Process Crash

### ISSUE THREAD

**Issue by eXpl0it3r** [jobbrIO/jobbr-server#106]
## Steps to Reproduce

1. Create a reoccurring trigger
2. Disable the trigger in the dashboard
3. Reenable the trigger in the dashboard
4. Wait for the next execution

## Actual Behavior

The process crashes with the following exception:

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'expression')
   at NCrontab.CrontabSchedule.TryParse[T](String expression, ParseOptions options, Func`2 valueSelector, Func`2 errorSelector)
   at NCrontab.CrontabSchedule.Parse(String expression, ParseOptions options)
   at Jobbr.Server.Scheduling.Planer.RecurringJobRunPlaner.Plan(RecurringTrigger trigger)
   at Jobbr.Server.Scheduling.DefaultScheduler.EvaluateRecurringTriggers()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

## Expected Behavior

The trigger successfully fires without server crash

**Comment by eXpl0it3r** [comment]
Root cause analysis:

When disabling the trigger on the Dashboard the WebApi is called, which das a converting from the web DTO to a trigger domain object. The DTO however doesn't contain all the information, e.g. the Definition isn't sent from the frontend to the backend, meaning the trigger information is overwritten with `NULL` in the DB and when the next scheduling tick, gets all the reoccurring triggers, it get a `NULL` value for the Cron Definition and crashes.

![image](https://github.com/jobbrIO/jobbr-server/assets/920861/d4bdfd76-79a2-458e-935c-d440f5fae52c)

Looking at this, I also spotted that `null` as string (not `NULL`) is written into the parameters field, as it does a serializing of a C# null string.

https://github.com/jobbrIO/jobbr-webapi/blob/a1576b4a16dfc90c4626b6d8730bdb59a5346441/source/Jobbr.Server.WebAPI/Controller/TriggerController.cs#L76-L91

**Comment by eXpl0it3r** [comment]
Fixed by https://github.com/jobbrIO/jobbr-webapi/pull/37
